export const GET_ACCESS_TOKEN_SPOTIFY = 'GET_ACCESS_TOKEN_SPOTIFY';
export const SUCCESS_GET_USER_PROFILE_SPOTIFY = 'SUCCESS_GET_USER_PROFILE_SPOTIFY';
export const SUCCESS_GET_DEVICE_ID = 'SUCCESS_GET_DEVICE_ID';
export const PLAY_TRACK = 'PLAY_TRACK';
export const PAUSE_TRACK = 'PAUSE_TRACK';
export const DATA_TRACK_FROM_SPOTIFY_SDK = 'DATA_TRACK_FROM_SPOTIFY_SDK';
