export const SEARCH_ARTISTS = 'SEARCH_ARTISTS';
export const SUCCESS_SEARCH_ARTISTS = 'SUCCESS_SEARCH_ARTISTS';
export const CLEAR_LIST_SEARCH = 'CLEAR_LIST_SEARCH';
export const NO_ARTIST_IN_DB = 'NO_ARTIST_IN_DB';
